### PR TITLE
SCRUM-5: Python Practice on different programs

### PR DESCRIPTION
**Pull request by venkat-duguru**
python practiced programs

### CODE REVIEW

**Comment by venkat-duguru** [comment]
please review the code above i have entered

**Review by maruthikumars — CHANGES_REQUESTED** [review]
please seperate automation in a separate repo

**Review by venkat-duguru — COMMENTED** [review]
I have done the changes to the files that are raised for review

**Comment by venkat-duguru** [comment]
> please separate automation in a separate repo
I have addressed

**Comment by venkat-duguru** [comment]
https://us05web.zoom.us/j/89146808402?pwd=bzZaK9NoaEu8Vb7eHPAcqmxI7pifca.1

**Pull request merged**
